all:
	javac Proj05_TestDriver.java
	javac Proj05_RedBlackNode.java
	javac Proj05_RedBlack_student.java
	javac RedBlackNode.java
	javac Proj05_HashTable_student.java
	javac test_hash.java

run:
	java test_hash

