all: 
	javac Proj01_BubbleSort.java
	javac Proj01_Main.java
	javac Proj01_InsertionSort.java
	javac Proj01_MergeSort.java
	javac Proj01_QuickSort.java
	javac Proj01_MergeSortBottomUp.java

run:
	java Proj01_Main < test1.dat
	java Proj01_Main < test2.dat
	java Proj01_Main < test3.dat
	java Proj01_Main < test4.dat
	java Proj01_Main < test5.dat
	java Proj01_Main < test6.dat

run2:
	java Proj01_Main < in_data.dat	
